services:
  weather.kellykemnitz.com:
    image: weather.kellykemnitz.com:latest
    container_name: weather
    networks:
      - kellyraspberrypi-local
    ports:
      - '8001:8001/tcp'
    deploy:
    restart: unless-stopped

networks:
  kellyraspberrypi-local:
    external: true
